language: node_js

notifications:
  email:
    on_success: change
    on_failure: change

node_js:
  - "0.12"

before_script: npm install raml-1-parser-test-utils@1.0.13 && node scriptDebug/platformTests.js && npm run devInstall

script: npm run buildall && npm run testall